# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Mod properties
mod_version = 2.0.14-alpha
maven_group = fr.tathan
archives_name = sky_aesthetics
enabled_platforms = fabric,neoforge

# Minecraft properties
# Minecraft properties
minecraft_version = 1.21.11

# Dependencies
fabric_loader_version = 0.18.3
fabric_api_version = 0.140.0
neoforge_version = 21.11.38-beta
modmenu_version=17.0.0-alpha.1
archivesName = sky_aesthetics
parchment_mapping_version=2025.10.12
#owo_version=0.12.20+1.21.4
#owo_version_neoforge=0.12.19-beta.2+1.21.4
exoconfig_version=0.3.0