# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Mod properties
mod_version = 2.0.18-beta
maven_group = fr.tathan
archives_name = sky_aesthetics
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2

# Dependencies
fabric_loader_version = 0.18.5
fabric_api_version = 0.150.0
neoforge_version = 26.1.2.71
modmenu_version=18.0.0-beta.1
exoconfig_version=0.3.1
#owo_version=0.12.20+1.21.4
#owo_version_neoforge=0.12.19-beta.2+1.21.4

archivesName = sky_aesthetics