package fr.tathan.sky_aesthetics.client.screens.editor.model;

import net.minecraft.resources.Identifier;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Optional;

/**
 * A working copy of a resource pack containing one or more {@link EditableSky skies}, one per
 * dimension. This is the unit the editor manages and {@link fr.tathan.sky_aesthetics.client.screens.editor.export.SkyPackExporter}
 * writes to disk.
 */
public class EditablePack {

    public String name = "My Sky Pack";
    public String description = "Generated by Sky Aesthetics";
    /** Optional path to a {@code pack.png} icon to copy into the pack. */
    public Optional<Path> iconPath = Optional.empty();

    public final List<EditableSky> skies = new ArrayList<>();

    public EditablePack() {
    }

    /** The on-disk folder name for the pack, derived from {@link #name}. */
    public String folderName() {
        String slug = name == null ? "" : name.trim().toLowerCase(Locale.ROOT)
                .replaceAll("[^a-z0-9-]+", "_")
                .replaceAll("^_|_$", "");
        return slug.isBlank() ? "sky_aesthetics_pack" : slug;
    }

    public EditableSky addSky() {
        EditableSky sky = new EditableSky();
        // Suggest a fresh, unique id so the new sky does not collide with existing ones.
        sky.skyId = uniqueId("sky_aesthetics:sky");
        skies.add(sky);
        return sky;
    }

    public EditableSky duplicate(EditableSky source) {
        EditableSky copy = EditableSky.fromProperties(source.toProperties());
        copy.skyId = uniqueId(stripTrailingNumber(copy.skyId));
        skies.add(copy);
        return copy;
    }

    public void remove(EditableSky sky) {
        skies.remove(sky);
    }

    private String uniqueId(String base) {
        String candidate = base;
        int n = 1;
        while (idExists(candidate)) {
            candidate = base + "_" + (++n);
        }
        return candidate;
    }

    private boolean idExists(String id) {
        for (EditableSky s : skies) {
            if (s.skyId.equals(id)) return true;
        }
        return false;
    }

    private static String stripTrailingNumber(String id) {
        return id.replaceAll("_\\d+$", "");
    }

    /**
     * Validates the pack before export. Returns a list of human-readable error messages; an empty
     * list means the pack is valid.
     */
    public List<String> validate() {
        List<String> errors = new ArrayList<>();
        if (skies.isEmpty()) {
            errors.add("The pack contains no skies.");
        }

        List<String> seenIds = new ArrayList<>();
        List<String> seenDimensions = new ArrayList<>();
        for (EditableSky sky : skies) {
            String label = sky.displayName();

            if (isBlank(sky.skyId)) {
                errors.add(label + ": sky id is empty.");
            } else if (Identifier.tryParse(sky.skyId) == null) {
                errors.add(label + ": invalid sky id '" + sky.skyId + "'.");
            } else if (seenIds.contains(sky.skyId)) {
                errors.add("Duplicate sky id '" + sky.skyId + "'.");
            } else {
                seenIds.add(sky.skyId);
            }

            if (isBlank(sky.dimension)) {
                errors.add(label + ": dimension is empty.");
            } else if (Identifier.tryParse(sky.dimension) == null) {
                errors.add(label + ": invalid dimension '" + sky.dimension + "'.");
            } else if (seenDimensions.contains(sky.dimension)) {
                errors.add("Two skies target the same dimension '" + sky.dimension + "'.");
            } else {
                seenDimensions.add(sky.dimension);
            }

            if (sky.sun.enabled && sky.sun.textureEnabled && !isBlank(sky.sun.texture)
                    && Identifier.tryParse(sky.sun.texture) == null) {
                errors.add(label + ": invalid sun texture '" + sky.sun.texture + "'.");
            }
            if (sky.moon.enabled && sky.moon.textureEnabled && !isBlank(sky.moon.texture)
                    && Identifier.tryParse(sky.moon.texture) == null) {
                errors.add(label + ": invalid moon texture '" + sky.moon.texture + "'.");
            }
            if (sky.skyBox.enabled && !isBlank(sky.skyBox.texture)
                    && Identifier.tryParse(sky.skyBox.texture) == null) {
                errors.add(label + ": invalid skybox texture '" + sky.skyBox.texture + "'.");
            }
            for (int i = 0; i < sky.skyObjects.size(); i++) {
                String tex = sky.skyObjects.get(i).texture;
                if (!isBlank(tex) && Identifier.tryParse(tex) == null) {
                    errors.add(label + ": sky object " + (i + 1) + " has invalid texture '" + tex + "'.");
                }
            }
        }
        return errors;
    }

    private static boolean isBlank(String s) {
        return s == null || s.isBlank();
    }
}
