modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/TathanDev/SkyAesthetics/issues"
license = "Insert License Here"

[[mods]]
modId = "sky_aesthetics"
version = "1.0.0"
displayName = "Sky Aesthetics"
authors = "The Stellaris Team"
description = '''
Change the skybox of Minecraft like you want !
'''
logoFile = "logo.png"

[[dependencies.sky_aesthetics]]
modId = "neoforge"
type = "required"
versionRange = "[20.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sky_aesthetics]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "sky_aesthetics.mixins.json"
