plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    runs {
        data {
            data()
            programArgs "--all", "--mod", "sky_aesthetics"
            programArgs "--output", project(":common").file("src/main/generated/resources").absolutePath
        }
    }

}

configurations {
    common
    shadowCommon

    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
    maven {
        url "https://modmaven.dev/"
        content {
            includeGroup "dev.technici4n"
        }
    }
}

dependencies {
    neoForge "net.neoforged:neoforge:$rootProject.neoforge_version"

    common(project(path: ':common')) { transitive false }
    shadowCommon(project(path: ':common', configuration: 'transformProductionNeoForge')) { transitive false }
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "sky_aesthetics.accessWidener"
    exclude "architectury.common.json"

    dependsOn jar
    mainSpec.sourcePaths.clear()       // Remove default source set inclusion
    from(zipTree(jar.archiveFile))     // Unpack jar output (preserves Loom modifications)
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null           // shadowJar becomes the main artifact
}

jar {
    archiveClassifier = "raw"
}

assemble.dependsOn shadowJar

configurations {
    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
}

sourcesJar {
    afterEvaluate {
        [":common"].forEach {
            def depSources = project(it).sourcesJar
            dependsOn depSources
            from(depSources.archiveFile.map { zipTree(it) }) {
                exclude "architectury.accessWidener"
            }
        }
    }
}

components.java {
    addVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {}
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}